# 2)	Faça um algoritmo que trate os dados em um pré-processamento e realize três modelos de classificação. Ao final deve apresentar as métricas de erro com o melhor resultado possível. -> Prever se pessoa saiu do pais

In [112]:
import pandas as pd
import matplotlib.pyplot as plt
from  sklearn.linear_model import LinearRegression
import sklearn.metrics
from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier


In [113]:

df = pd.read_csv("Churn_Modelling.csv")
df = df.dropna()
df = df.drop(columns=["CustomerId","Surname","RowNumber","Gender"])
df


CreditScore Geography  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619    France   42       2       0.00              1          1   
1             608     Spain   41       1   83807.86              1          0   
2             502    France   42       8  159660.80              3          1   
3             699    France   39       1       0.00              2          0   
4             850     Spain   43       2  125510.82              1          1   
...           ...       ...  ...     ...        ...            ...        ...   
9995          771    France   39       5       0.00              2          1   
9996          516    France   35      10   57369.61              1          1   
9997          709    France   36       7       0.00              1          0   
9998          772   Germany   42       3   75075.31              2          1   
9999          792    France   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  
0                  1        101348.88       1  
1                  1        112542.58       0  
2                  0        113931.57       1  
3                  0         93826.63       0  
4                  1         79084.10       0  
...              ...              ...     ...  
9995               0         96270.64       0  
9996               1        101699.77       0  
9997               1         42085.58       1  
9998               0         92888.52       1  
9999               0         38190.78       0  

[10000 rows x 10 columns]

In [123]:

LABELS = df.columns  

encoder = LabelEncoder()
for col in LABELS:
    if df[col].dtype == 'O':
        df[col] = encoder.fit_transform(df[col])
    elif df[col].dtype == 'bool':
        df[col] = df[col].astype('int')

x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values.reshape(-1,1)


x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.20)



# Logistic Regression

In [124]:
clf = LogisticRegression()
clf.fit(x_train,y_train.ravel())

print(f"{'='*20} Decision Tree {'='*20}")
print(f"Score: {clf.score(x_test,y_test)}")
print("Matrix de confusao:")
print(confusion_matrix(y_test,clf.predict(x_test)))
print("--Metricas--")
print(f"Acuracia: {accuracy_score(y_test,clf.predict(x_test)) *100:.2f}%")
print(f"Precisao: {precision_score(y_test,clf.predict(x_test))*100:.2f}%")
print(f"Recall :{recall_score(y_test,clf.predict(x_test))*100:.2f}%")
print(f"F1 : {f1_score(y_test,clf.predict(x_test))*100:.2f}%")

==================== Decision Tree ====================
Score: 0.789
Matrix de confusao:
[[1563   38]
 [ 384   15]]
--Metricas--
Acuracia: 78.90%
Precisao: 28.30%
Recall :3.76%
F1 : 6.64%


# Decision Tree

In [125]:
dtree = DecisionTreeClassifier()
dtree.fit(x_train,y_train.ravel())

print(f"{'='*20} Decision Tree {'='*20}")
print(f"Score: {dtree.score(x_test,y_test)}")
print("Matrix de confusao:")
print(confusion_matrix(y_test,dtree.predict(x_test)))
print("--Metricas--")
print(f"Acuracia: {accuracy_score(y_test,dtree.predict(x_test)) *100:.2f}%")
print(f"Precisao: {precision_score(y_test,dtree.predict(x_test))*100:.2f}%")
print(f"Recall :{recall_score(y_test,dtree.predict(x_test))*100:.2f}%")
print(f"F1 : {f1_score(y_test,dtree.predict(x_test))*100:.2f}%")

==================== Decision Tree ====================
Score: 0.805
Matrix de confusao:
[[1395  206]
 [ 184  215]]
--Metricas--
Acuracia: 80.50%
Precisao: 51.07%
Recall :53.88%
F1 : 52.44%


#  KNeighbors


In [126]:
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(x_train,y_train.ravel())

print(f"{'='*20} Decision Tree {'='*20}")
print(f"Score: {neigh.score(x_test,y_test)}")
print("Matrix de confusao:")
print(confusion_matrix(y_test,neigh.predict(x_test)))
print("--Metricas--")
print(f"Acuracia: {accuracy_score(y_test,neigh.predict(x_test)) *100:.2f}%")
print(f"Precisao: {precision_score(y_test,neigh.predict(x_test))*100:.2f}%")
print(f"Recall :{recall_score(y_test,neigh.predict(x_test))*100:.2f}%")
print(f"F1 : {f1_score(y_test,neigh.predict(x_test))*100:.2f}%")

==================== Decision Tree ====================
Score: 0.728
Matrix de confusao:
[[1409  192]
 [ 352   47]]
--Metricas--
Acuracia: 72.80%
Precisao: 19.67%
Recall :11.78%
F1 : 14.73%
